baseurl = "/"
author = "Philip Huebner"
title = "L&L Lab"
languageCode = "en-us"
theme = "foundation-theme"
enableRobotsTXT = true
SectionPagesMenu = ["main", "social"]
publishDir = "lab_website"

[params.meta]
description = "UIUC Learning & Language Lab"
keywords = "SRN, Jon Willits, Jessica Montag, neural network, language acquisition, UIUC"

[params.hero]
herotitle = "ğŸ†„ğŸ…¸ğŸ†„ğŸ…² ğŸ…»ğŸ…´ğŸ…°ğŸ†ğŸ…½ğŸ…¸ğŸ…½ğŸ…¶ & ğŸ…»ğŸ…°ğŸ…½ğŸ…¶ğŸ†„ğŸ…°ğŸ…¶ğŸ…´ ğŸ…»ğŸ…°ğŸ…±"
herodiscription = ""
btnblue = "For Researchers"
btngreen = "For Parents"

[params.main]
contentOneTitle = "Welcome to the UIUC Learning & Language Lab"
contentOneBody = ""
contentTwoBody = "Our mission is to better understand how children acquire concepts, learn to comprehend and produce language. "


[params.footer]
email = "info@philhuebner.com"
address = "Champaign, IL"

[[menu.main]]
name = "About"
url = "/about"

[[menu.main]]
name = "Topics"
url = "/research"

[[menu.main]]
name = "Publications"
url = "/publications"

[[menu.main]]
name = "Members"
url = "/members"

[[menu.main]]
name = "Participate"
url = "/participate"

[[menu.main]]
name = "Join"
url = "/join"

[[menu.social]]
name = "Facebook"
url = "http://facebook.com"

[[menu.social]]
name = "Github"
url = "https://github.com/UIUCLearningLanguageLab"

